### PR TITLE
Update killercoda scenarios after breaking changes in k3s

### LINKED ISSUE #46: Update Killercoda scenarios from deprecated k3s profiles
Email from Killercoda:

We're writing you because you've some scenarios based on K3s environments.

As recently announced these have been deprecated. Please check here for more details and how to migrate.

We suggest to go ahead and change your imageid to "kubernetes-kubeadm-1node" or "kubernetes-kubeadm-1node-4GB".

From the 20.01.2024, all K3s scenarios will automatically be run on corresponding Kubeadm environments. If you don't rely on K3s specifically, nothing should break.

You could also use our "ubuntu" environments and install K3s yourself in foreground or background scripts.

### PR DESCRIPTION
**Pull request by cwilkers**
**What this PR does / why we need it**:

Fixes broken killercoda scenarios

  * Corrects test for k3s installed
  * Updates to default ubuntu 4g image

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #46 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by cwilkers** [comment]
/hold

Something is wrong with the cdi lab after rebase.

**Comment by cwilkers** [comment]
Hold has been released, current branch is working, reviewers can test at:

http://killercoda.com/cwilkers/

**Comment by jobbler** [comment]
@cwilkers I tried the link provided to run through the scenarios. The 101 scenario did not finish waiting for the .kube/* file to exist. After 10 minutes, I exited the scenario.

The cdi scenario worked fine.

**Comment by jobbler** [comment]
just ran through both tests again. they seem to work fine.

/lgtm

**Review by jobbler — APPROVED** [review]
the scenarios seem to work fine.

**Pull request merged**
