### PR TITLE
Completed the KubeVirt lab update.

### PR DESCRIPTION
**Pull request by hindu-muppala**
@cwilkers ,I tested the lab in killerconda.And test is successful. Please review and recommend changes if required.

### CODE REVIEW

**Comment by hindu-muppala** [comment]
@cwilkers ,I commited the changes from the **laptop** but  I'm not getting why **doc-signoff:no**. But the link mention in the bot is **not working**. Please, **KubeVirt** team help me out to solve this problem. I tried but none of them worked.

**Comment by hindu-muppala** [comment]
Because, I solved the issue as *best as possible*.

**Comment by cwilkers** [comment]
Oh, we'll need to raise an issue on that missing contributor guide. In the meantime, you can check out https://github.com/kubevirt/kubevirt/blob/main/CONTRIBUTING.md#contributor-compliance-with-developer-certificate-of-origin-dco

**Comment by cwilkers** [comment]
The easiest way to get it working is to go to your git log and count all your commits, then do an interactive rebase of all the commits you have. Make sure to add --signoff (or -s) to the rebase command. Check out https://www.git-tower.com/learn/git/faq/git-squash for a good guide on the interactive rebase / squash commit feature.

**Pull request closed without merging**
