### PR TITLE
Sign off problem solved

### PR DESCRIPTION
**Pull request by hindu-muppala**
Sign off problem solved. I learnt more about kubeVirt and Git in solving this pull request. Thank you @cwilkers ,for guidance.

### CODE REVIEW

**Comment by cwilkers** [comment]
/remove-lifecycle stale
I'm testing in my profile, we'll need to add the lesson to /structure.json for one thing.

**Comment by cwilkers** [comment]
I just ran into a problem: instead of 0.56, the scenario starts with v1.0.0

**Comment by cwilkers** [comment]
Another problem, the instructions in step2 are pretty confusing. Changing the image tag version doesn't actually cause any changes, you have to do that AND update the operator by applying newly downloaded yaml.

**Comment by cwilkers** [comment]
While playing with the scenario to get this working, I found the following bit of jq magic useful:
```
kubectl get deployment.apps -n kubevirt -o json | jq -c '.items[] | .spec.template.spec.containers[] | .image'
```

**Comment by hindu-muppala** [comment]
@cwilkers , I want sometime for the suggested changes to do. Please guide me, If I got any problem while solving,

**Comment by cwilkers** [comment]
have a look at my branch, I fixed some of the issues and have it set up at killercoda/cwilkers

https://github.com/cwilkers/katacoda-scenarios/tree/hindu-muppala-update-lab

**Pull request closed without merging**
