### PR TITLE
Updated lab

### PR DESCRIPTION
**Pull request by hindu-muppala**
changed the lab code such that the lab update from v0.56.1 to v0.57.0. Testing is still incomplete .

### CODE REVIEW

**Comment by hindu-muppala** [comment]
@cwilkers ,please if you review I will test soon.

**Comment by cwilkers** [comment]
Ooh, I didn't mean to push to your repository, I was trying to test on my own (because I have a killercoda account with access to the large RAM machines we need for KubeVirt)

We would have eventually needed to incorporate these changes, but I wanted discuss with you first. Apologies for the accidental pushes.

**Comment by cwilkers** [comment]
I have set up my personal killercoda account to point to a branch where I duplicate your branch. You can access the demo as rendered by Killercoda at https://killercoda.com/cwilkers

One major change I would suggest (but not absolutely require):
In the CDI lab, we skip the install of KubeVirt by handling that in the background.sh that starts when the scenario boots up. There is a script in foreground.sh that watches for the install to succeed before turning the shell over to the user.

I think it would be really helpful to apply this logic to the Upgrading lab, by having background.sh install the older version of KubeVirt so the user doesn't have to click through that part themselves.

What do you think @hindu-muppala ?

**Comment by hindu-muppala** [comment]
@cwilkers ,definately I will do like CDI lab  as suggested .

**Comment by cwilkers** [comment]
Hi @hindu-muppala , unfortunately, your last two commits did not have the sign-off added to them, and now our CI's DCO check is failing. Can you amend your commits to signoff both? (or squash the last two commits into one, where you signoff?)

**Comment by cwilkers** [comment]
I'm going through the lab on my own account, and ran into an issue: we use virtctl to start the VM, but we do not download virtctl first, so it's a command not found error.

**Comment by hindu-muppala** [comment]
@cwilkers , I will complete this issue in next two days. I'm busy in last two months, so I didn't completed.

**Comment by hindu-muppala** [comment]
Signed-off-by: Hindu hindumuppala@gmail.com

**Comment by hindu-muppala** [comment]
@cwilkers ,

> Hi @hindu-muppala , unfortunately, your last two commits did not have the sign-off added to them, and now our CI's DCO check is failing. Can you amend your commits to signoff both? (or squash the last two commits into one, where you signoff?)

I will sign off by today

**Review by hindu-muppala — COMMENTED** [review]
Signed-off-by: Hindu Muppala <hindumuppala@gmail.com>

**Review by hindu-muppala — COMMENTED** [review]
Signed-off-by: Hindu Muppala <hindumuppala@gmail.com>

**Review by hindu-muppala — COMMENTED** [review]
Signed-off-by: Hindu Muppala <hindumuppala@gmail.com>

**Comment by hindu-muppala** [comment]
> Hi @hindu-muppala , unfortunately, your last two commits did not have the sign-off added to them, and now our CI's DCO check is failing. Can you amend your commits to signoff both? (or squash the last two commits into one, where you signoff?)

@cwilkers ,is the problem solved now.

**Comment by hindu-muppala** [comment]
> I'm going through the lab on my own account, and ran into an issue: we use virtctl to start the VM, but we do not download virtctl first, so it's a command not found error.

If any one not working, I will work on this.

**Comment by hindu-muppala** [comment]
image
@cwilkers ,I started doing to solve the problems we faced . But, I'm getting this error. Please help me to know the error.So, that I will complete my work as soon as possible. I opened account in my name and started testing the lab scenarios.
https://killercoda.com/hindu/scenario/kubevirt-cdi

**Comment by cwilkers** [comment]
That seems like  an internal problem with the killercoda service. I would recommend waiting and trying again. If the error persists, reach out to their support as described at https://killercoda.com/support

**Pull request closed without merging**
