### PR TITLE
Update Owners

### PR DESCRIPTION
**Pull request by iranzo**
Update Owners

Signed-off-by: Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>

### CODE REVIEW

**Comment by ptrnull** [comment]
/lgtm
/approve
bye bye @jparrill , hello @alosadagrande

**Comment by jparrill** [comment]
This is not a goodbye, just a see you later xD
/lgtm

**Comment by jparrill** [comment]
It's Tide aware of this repo to manage self-merging?

**Comment by iranzo** [comment]
> It's Tide aware of this repo to manage self-merging?

No, the prior mantainer didn't worked on this :joy:

**Comment by iranzo** [comment]
@jparrill https://github.com/kubevirt/project-infra/pull/250  ;-)

**Pull request merged**
